# Generated by Django 5.0.1 on 2024-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_appoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='status',
            field=models.CharField(default='PENDING', max_length=250),
        ),
    ]
