from . import views
from django.urls import path,include

urlpatterns = [
    path('', views.HomePage, name='HomePage'),
    path('LoginPage/', views.LoginPage, name='LoginPage'),
    path('RegisterPatientPage/', views.RegisterPatientPage, name='RegisterPatientPage'),
    path('RegisterDoctorPage/', views.RegisterDoctorPage, name='RegisterDoctorPage'),
    path('PatientRegistration/', views.PatientRegistration, name='PatientRegistration'),
    path('DoctorRegistration/', views.DoctorRegistration, name='DoctorRegistration'),
    path('main_login/', views.main_login, name='main_login'),
    path('AdminHome/', views.AdminHome, name='AdminHome'),
    path('approve_disapprove_users/',views.approve_disapprove_users,name='approve_disapprove_users'),
    path('manage_department/',views.manage_department,name='manage_department'),
    path('edit_department/<int:pk>',views.edit_department,name='edit_department'),
    path('update_department/<int:pk>',views.update_department,name='update_department'),
    path('add_department/',views.add_department,name='add_department'),
    path('reg_department/',views.reg_department,name='reg_department'),
    path('view_cv/<int:pk>',views.view_cv,name='view_cv'),
    path('doctor_details/',views.doctor_details,name='doctor_details'),
    path('delete_doct/<int:pk>',views.delete_doct,name='delete_doct'),
    path('DoctorHome/',views.DoctorHome,name='DoctorHome'),
    path('Doctor_Leave/',views.Doctor_Leave,name='Doctor_Leave'),
    path('PatientHome/',views.PatientHome,name='PatientHome'),
    path('BookAppoinment/',views.BookAppoinment,name='BookAppoinment'),
    path('ChooseDoctor/', views.ChooseDoctor,name='ChooseDoctor'),
    path('ConfirmBooking/', views.ConfirmBooking,name='ConfirmBooking'),
    path('ApproveAppoinments/', views.ApproveAppoinments,name='ApproveAppoinments'),
    path('ViewDoctorLeave/', views.ViewDoctorLeave,name='ViewDoctorLeave'),
    path('DoctorLeaveRecord/', views.DoctorLeaveRecord,name='DoctorLeaveRecord'),
    path('ViewDoctorAppoinment/', views.ViewDoctorAppoinment,name='ViewDoctorAppoinment'),
    path('DoctorAppoinmentRecord/', views.DoctorAppoinmentRecord,name='DoctorAppoinmentRecord'),
    path('PatientAppoinmentRecord/', views.PatientAppoinmentRecord,name='PatientAppoinmentRecord'),
    path('DoctorAppoinments/', views.DoctorAppoinments,name='DoctorAppoinments'),
    path('DoctorAppoinmentsPage/', views.DoctorAppoinmentsPage,name='DoctorAppoinmentsPage'),
    path('ViewPatientAppoinment/', views.ViewPatientAppoinment,name='ViewPatientAppoinment'),
    path('AppoinmentRecordPatient/', views.AppoinmentRecordPatient,name='AppoinmentRecordPatient'),
    path('DoctorPatientAppoinment/', views.DoctorPatientAppoinment,name='DoctorPatientAppoinment'),
    path('DoctorPatientRecord/', views.DoctorPatientRecord,name='DoctorPatientRecord'),
    path('AdminPatientAppoinment/', views.AdminPatientAppoinment,name='AdminPatientAppoinment'),
    path('AdminPatientRecord/', views.AdminPatientRecord,name='AdminPatientRecord'),
    path('AllAppoinmentRecordPatient/', views.AllAppoinmentRecordPatient,name='AllAppoinmentRecordPatient'),
    path('Notifications/', views.Notifications,name='Notifications'),
    path('patient_details/', views.patient_details,name='patient_details'),
    path('delete_pat/<int:pk>', views.delete_pat,name='delete_pat'),
    path('logout/', views.logout,name='logout'),
    path('edit_doctor_profile/', views.edit_doctor_profile,name='edit_doctor_profile'),
    path('update_doctor_profile/', views.update_doctor_profile,name='update_doctor_profile'),
    path('reset_passwords/', views.reset_passwords,name='reset_passwords'),
    path('reset_password/', views.reset_password,name='reset_password'),
    path('edit_patient_profile/', views.edit_patient_profile,name='edit_patient_profile'),
    path('update_patient_profile/', views.update_patient_profile,name='update_patient_profile'),
    path('reset_patients_passwords/', views.reset_patients_passwords,name='reset_patients_passwords'),
    path('reset_password_patient/', views.reset_password_patient,name='reset_password_patient'),
    path('AppoinmentDoctor/', views.AppoinmentDoctor,name='AppoinmentDoctor'),
    path('AppoinmentDoctorReport/', views.AppoinmentDoctorReport,name='AppoinmentDoctorReport'),
    path('DateAppoinment/', views.DateAppoinment,name='DateAppoinment'),
    path('DateAppoinmentReport/', views.DateAppoinmentReport,name='DateAppoinmentReport'),
    path('AddDoctorPage/', views.AddDoctorPage,name='AddDoctorPage'),
    path('AddDoctor/', views.AddDoctor,name='AddDoctor'),
    path('AddPatientPage/', views.AddPatientPage,name='AddPatientPage'),
    path('AddPatient/', views.AddPatient,name='AddPatient'),



]